theme: # Not using a theme
title: 2GETHER
description: Site internet de l'association 2GETHER.
lang: fr
author: Matiboux
exclude:
- README.md
discord:
  id: 778692492644188211
  link: https://discord.gg/J8Uv6pkaY5
